source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'mysql2'
gem 'jquery-rails'

gem 'devise'
gem 'cancan'

gem 'rvm'
gem 'therubyracer'

gem 'roles_ui', path: '../../'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'thin'
end

group :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'database_cleaner'
end
